<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8ba7136294f3558bf2c65ac183035533
{
    public static $prefixLengthsPsr4 = array (
        'H' => 
        array (
            'Hp\\Www\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Hp\\Www\\' => 
        array (
            0 => __DIR__ . '/../..' . '/myphp',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8ba7136294f3558bf2c65ac183035533::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8ba7136294f3558bf2c65ac183035533::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8ba7136294f3558bf2c65ac183035533::$classMap;

        }, null, ClassLoader::class);
    }
}
